spring:
  profiles:
    active: dev
    include: secret
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jackson:
    serialization:
      fail-on-empty-beans: false
  threads:
    virtual:
      enabled: true
  sql:
    init:
      mode: always
      continue-on-error: true
      data-locations: classpath:/sql/data1.sql, classpath:/sql/data2.sql, classpath:/sql/data3.sql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    open-in-view: false
    defer-datasource-initialization: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: <ON_SECRET>
            scope: profile_nickname, profile_image
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: '${custom.site.backUrl}/{action}/oauth2/code/{registrationId}'
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
custom:
  dev:
    cookieDomain: localhost
    frontUrl: "http://${custom.dev.cookieDomain}:3000"
    backUrl: "http://${custom.dev.cookieDomain}:${server.port}"
  prod:
    cookieDomain: eitcharge.site
    frontUrl: "https://${custom.prod.cookieDomain}"
    backUrl: "https://api.${custom.prod.cookieDomain}"
  site:
    cookieDomain: "${custom.dev.cookieDomain}"
    frontUrl: "${custom.dev.frontUrl}"
    backUrl: "${custom.dev.backUrl}"
    name: eitcharge
  jwt:
    secretKey: <ON_SECRET>
  accessToken:
    expirationSec: '#{60*60}'
  temp:
    dirPath: c:/temp/eitcharge_dev/temp
  genFile:
    dirPath: c:/temp/eitcharge_dev
  api:
    serviceKey: <ON_SECRET>