server:
  shutdown: graceful
spring:
  datasource:
    url: jdbc:mysql://172.17.0.1:3306/eitcharge_prod
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
custom:
  site:
    cookieDomain: "${custom.prod.cookieDomain}"
    frontUrl: "${custom.prod.frontUrl}"
    backUrl: "${custom.prod.backUrl}"
  temp:
    dirPath: c:/temp/eitcharge_prod/temp
  genFile:
    dirPath: c:/temp/eitcharge_prod